// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "bc_mult_448.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic bc_mult_448::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic bc_mult_448::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> bc_mult_448::ap_ST_fsm_state1 = "1";
const sc_lv<8> bc_mult_448::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<8> bc_mult_448::ap_ST_fsm_state5 = "100";
const sc_lv<8> bc_mult_448::ap_ST_fsm_state6 = "1000";
const sc_lv<8> bc_mult_448::ap_ST_fsm_state7 = "10000";
const sc_lv<8> bc_mult_448::ap_ST_fsm_state8 = "100000";
const sc_lv<8> bc_mult_448::ap_ST_fsm_state9 = "1000000";
const sc_lv<8> bc_mult_448::ap_ST_fsm_state10 = "10000000";
const bool bc_mult_448::ap_const_boolean_1 = true;
const sc_lv<32> bc_mult_448::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> bc_mult_448::ap_const_lv32_1 = "1";
const bool bc_mult_448::ap_const_boolean_0 = false;
const sc_lv<1> bc_mult_448::ap_const_lv1_0 = "0";
const sc_lv<32> bc_mult_448::ap_const_lv32_3 = "11";
const sc_lv<32> bc_mult_448::ap_const_lv32_4 = "100";
const sc_lv<32> bc_mult_448::ap_const_lv32_5 = "101";
const sc_lv<32> bc_mult_448::ap_const_lv32_6 = "110";
const sc_lv<1> bc_mult_448::ap_const_lv1_1 = "1";
const sc_lv<4> bc_mult_448::ap_const_lv4_0 = "0000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> bc_mult_448::ap_const_lv32_2 = "10";
const sc_lv<3> bc_mult_448::ap_const_lv3_0 = "000";
const sc_lv<3> bc_mult_448::ap_const_lv3_1 = "1";
const sc_lv<3> bc_mult_448::ap_const_lv3_2 = "10";
const sc_lv<3> bc_mult_448::ap_const_lv3_3 = "11";
const sc_lv<3> bc_mult_448::ap_const_lv3_4 = "100";
const sc_lv<3> bc_mult_448::ap_const_lv3_5 = "101";
const sc_lv<3> bc_mult_448::ap_const_lv3_6 = "110";
const sc_lv<3> bc_mult_448::ap_const_lv3_7 = "111";
const sc_lv<32> bc_mult_448::ap_const_lv32_38 = "111000";
const sc_lv<32> bc_mult_448::ap_const_lv32_6F = "1101111";
const sc_lv<32> bc_mult_448::ap_const_lv32_70 = "1110000";
const sc_lv<32> bc_mult_448::ap_const_lv32_A7 = "10100111";
const sc_lv<32> bc_mult_448::ap_const_lv32_A8 = "10101000";
const sc_lv<32> bc_mult_448::ap_const_lv32_DF = "11011111";
const sc_lv<32> bc_mult_448::ap_const_lv32_E0 = "11100000";
const sc_lv<32> bc_mult_448::ap_const_lv32_117 = "100010111";
const sc_lv<32> bc_mult_448::ap_const_lv32_118 = "100011000";
const sc_lv<32> bc_mult_448::ap_const_lv32_14F = "101001111";
const sc_lv<32> bc_mult_448::ap_const_lv32_150 = "101010000";
const sc_lv<32> bc_mult_448::ap_const_lv32_187 = "110000111";
const sc_lv<32> bc_mult_448::ap_const_lv32_188 = "110001000";
const sc_lv<32> bc_mult_448::ap_const_lv32_1BF = "110111111";
const sc_lv<4> bc_mult_448::ap_const_lv4_8 = "1000";
const sc_lv<4> bc_mult_448::ap_const_lv4_1 = "1";
const sc_lv<56> bc_mult_448::ap_const_lv56_0 = "00000000000000000000000000000000000000000000000000000000";
const sc_lv<112> bc_mult_448::ap_const_lv112_0 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<168> bc_mult_448::ap_const_lv168_lc_1 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<224> bc_mult_448::ap_const_lv224_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<280> bc_mult_448::ap_const_lv280_lc_1 = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<336> bc_mult_448::ap_const_lv336_lc_1 = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<392> bc_mult_448::ap_const_lv392_lc_1 = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_2 = "111000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_3 = "1110000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_4 = "10101000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_5 = "11100000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_6 = "100011000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_7 = "101010000";
const sc_lv<896> bc_mult_448::ap_const_lv896_lc_8 = "110001000";
const sc_lv<32> bc_mult_448::ap_const_lv32_7 = "111";

bc_mult_448::bc_mult_448(sc_module_name name) : sc_module(name), mVcdFile(0) {
    eval_4_isog_mux_8bkb_U1 = new eval_4_isog_mux_8bkb<1,1,56,56,56,56,56,56,56,56,3,56>("eval_4_isog_mux_8bkb_U1");
    eval_4_isog_mux_8bkb_U1->din0(bi_0_V_reg_2075);
    eval_4_isog_mux_8bkb_U1->din1(bi_1_V_reg_2080);
    eval_4_isog_mux_8bkb_U1->din2(bi_2_V_reg_2085);
    eval_4_isog_mux_8bkb_U1->din3(bi_3_V_reg_2090);
    eval_4_isog_mux_8bkb_U1->din4(bi_4_V_reg_2095);
    eval_4_isog_mux_8bkb_U1->din5(bi_5_V_reg_2100);
    eval_4_isog_mux_8bkb_U1->din6(bi_6_V_reg_2105);
    eval_4_isog_mux_8bkb_U1->din7(bi_7_V_reg_2110);
    eval_4_isog_mux_8bkb_U1->din8(tmp_1_fu_710_p9);
    eval_4_isog_mux_8bkb_U1->dout(tmp_1_fu_710_p10);
    eval_4_isog_mul_5cud_U2 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U2");
    eval_4_isog_mul_5cud_U2->clk(ap_clk);
    eval_4_isog_mul_5cud_U2->reset(ap_rst);
    eval_4_isog_mul_5cud_U2->din0(grp_fu_727_p0);
    eval_4_isog_mul_5cud_U2->din1(grp_fu_727_p1);
    eval_4_isog_mul_5cud_U2->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U2->dout(grp_fu_727_p2);
    eval_4_isog_mul_5cud_U3 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U3");
    eval_4_isog_mul_5cud_U3->clk(ap_clk);
    eval_4_isog_mul_5cud_U3->reset(ap_rst);
    eval_4_isog_mul_5cud_U3->din0(grp_fu_732_p0);
    eval_4_isog_mul_5cud_U3->din1(grp_fu_732_p1);
    eval_4_isog_mul_5cud_U3->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U3->dout(grp_fu_732_p2);
    eval_4_isog_mul_5cud_U4 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U4");
    eval_4_isog_mul_5cud_U4->clk(ap_clk);
    eval_4_isog_mul_5cud_U4->reset(ap_rst);
    eval_4_isog_mul_5cud_U4->din0(grp_fu_737_p0);
    eval_4_isog_mul_5cud_U4->din1(grp_fu_737_p1);
    eval_4_isog_mul_5cud_U4->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U4->dout(grp_fu_737_p2);
    eval_4_isog_mul_5cud_U5 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U5");
    eval_4_isog_mul_5cud_U5->clk(ap_clk);
    eval_4_isog_mul_5cud_U5->reset(ap_rst);
    eval_4_isog_mul_5cud_U5->din0(grp_fu_742_p0);
    eval_4_isog_mul_5cud_U5->din1(grp_fu_742_p1);
    eval_4_isog_mul_5cud_U5->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U5->dout(grp_fu_742_p2);
    eval_4_isog_mul_5cud_U6 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U6");
    eval_4_isog_mul_5cud_U6->clk(ap_clk);
    eval_4_isog_mul_5cud_U6->reset(ap_rst);
    eval_4_isog_mul_5cud_U6->din0(grp_fu_747_p0);
    eval_4_isog_mul_5cud_U6->din1(grp_fu_747_p1);
    eval_4_isog_mul_5cud_U6->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U6->dout(grp_fu_747_p2);
    eval_4_isog_mul_5cud_U7 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U7");
    eval_4_isog_mul_5cud_U7->clk(ap_clk);
    eval_4_isog_mul_5cud_U7->reset(ap_rst);
    eval_4_isog_mul_5cud_U7->din0(grp_fu_752_p0);
    eval_4_isog_mul_5cud_U7->din1(grp_fu_752_p1);
    eval_4_isog_mul_5cud_U7->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U7->dout(grp_fu_752_p2);
    eval_4_isog_mul_5cud_U8 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U8");
    eval_4_isog_mul_5cud_U8->clk(ap_clk);
    eval_4_isog_mul_5cud_U8->reset(ap_rst);
    eval_4_isog_mul_5cud_U8->din0(grp_fu_757_p0);
    eval_4_isog_mul_5cud_U8->din1(grp_fu_757_p1);
    eval_4_isog_mul_5cud_U8->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U8->dout(grp_fu_757_p2);
    eval_4_isog_mul_5cud_U9 = new eval_4_isog_mul_5cud<1,2,56,56,112>("eval_4_isog_mul_5cud_U9");
    eval_4_isog_mul_5cud_U9->clk(ap_clk);
    eval_4_isog_mul_5cud_U9->reset(ap_rst);
    eval_4_isog_mul_5cud_U9->din0(grp_fu_762_p0);
    eval_4_isog_mul_5cud_U9->din1(grp_fu_762_p1);
    eval_4_isog_mul_5cud_U9->ce(ap_var_for_const0);
    eval_4_isog_mul_5cud_U9->dout(grp_fu_762_p2);
    eval_4_isog_mux_8dEe_U10 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U10");
    eval_4_isog_mux_8dEe_U10->din0(partial_products_7_7_fu_128);
    eval_4_isog_mux_8dEe_U10->din1(partial_products_0_6_fu_132);
    eval_4_isog_mux_8dEe_U10->din2(partial_products_0_5_fu_136);
    eval_4_isog_mux_8dEe_U10->din3(partial_products_0_4_fu_140);
    eval_4_isog_mux_8dEe_U10->din4(partial_products_0_3_fu_144);
    eval_4_isog_mux_8dEe_U10->din5(partial_products_0_2_fu_148);
    eval_4_isog_mux_8dEe_U10->din6(partial_products_0_1_fu_152);
    eval_4_isog_mux_8dEe_U10->din7(partial_products_0_s_fu_156);
    eval_4_isog_mux_8dEe_U10->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U10->dout(tmp_2_fu_1383_p10);
    eval_4_isog_add_8eOg_U11 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U11");
    eval_4_isog_add_8eOg_U11->clk(ap_clk);
    eval_4_isog_add_8eOg_U11->reset(ap_rst);
    eval_4_isog_add_8eOg_U11->din0(tmp_2_fu_1383_p10);
    eval_4_isog_add_8eOg_U11->din1(sum_V_0_0_reg_407);
    eval_4_isog_add_8eOg_U11->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U11->dout(grp_fu_1405_p2);
    eval_4_isog_mux_8dEe_U12 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U12");
    eval_4_isog_mux_8dEe_U12->din0(partial_products_7_8_fu_160);
    eval_4_isog_mux_8dEe_U12->din1(partial_products_1_6_fu_164);
    eval_4_isog_mux_8dEe_U12->din2(partial_products_1_5_fu_168);
    eval_4_isog_mux_8dEe_U12->din3(partial_products_1_4_fu_172);
    eval_4_isog_mux_8dEe_U12->din4(partial_products_1_3_fu_176);
    eval_4_isog_mux_8dEe_U12->din5(partial_products_1_2_fu_180);
    eval_4_isog_mux_8dEe_U12->din6(partial_products_1_1_fu_184);
    eval_4_isog_mux_8dEe_U12->din7(partial_products_1_s_fu_188);
    eval_4_isog_mux_8dEe_U12->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U12->dout(tmp_3_fu_1411_p10);
    eval_4_isog_add_8eOg_U13 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U13");
    eval_4_isog_add_8eOg_U13->clk(ap_clk);
    eval_4_isog_add_8eOg_U13->reset(ap_rst);
    eval_4_isog_add_8eOg_U13->din0(grp_fu_1439_p0);
    eval_4_isog_add_8eOg_U13->din1(sum_V_1_0_reg_419);
    eval_4_isog_add_8eOg_U13->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U13->dout(grp_fu_1439_p2);
    eval_4_isog_mux_8dEe_U14 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U14");
    eval_4_isog_mux_8dEe_U14->din0(partial_products_7_9_fu_192);
    eval_4_isog_mux_8dEe_U14->din1(partial_products_2_6_fu_196);
    eval_4_isog_mux_8dEe_U14->din2(partial_products_2_5_fu_200);
    eval_4_isog_mux_8dEe_U14->din3(partial_products_2_4_fu_204);
    eval_4_isog_mux_8dEe_U14->din4(partial_products_2_3_fu_208);
    eval_4_isog_mux_8dEe_U14->din5(partial_products_2_2_fu_212);
    eval_4_isog_mux_8dEe_U14->din6(partial_products_2_1_fu_216);
    eval_4_isog_mux_8dEe_U14->din7(partial_products_2_s_fu_220);
    eval_4_isog_mux_8dEe_U14->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U14->dout(tmp_4_fu_1445_p10);
    eval_4_isog_add_8eOg_U15 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U15");
    eval_4_isog_add_8eOg_U15->clk(ap_clk);
    eval_4_isog_add_8eOg_U15->reset(ap_rst);
    eval_4_isog_add_8eOg_U15->din0(grp_fu_1473_p0);
    eval_4_isog_add_8eOg_U15->din1(sum_V_2_0_reg_431);
    eval_4_isog_add_8eOg_U15->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U15->dout(grp_fu_1473_p2);
    eval_4_isog_mux_8dEe_U16 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U16");
    eval_4_isog_mux_8dEe_U16->din0(partial_products_7_10_fu_224);
    eval_4_isog_mux_8dEe_U16->din1(partial_products_3_6_fu_228);
    eval_4_isog_mux_8dEe_U16->din2(partial_products_3_5_fu_232);
    eval_4_isog_mux_8dEe_U16->din3(partial_products_3_4_fu_236);
    eval_4_isog_mux_8dEe_U16->din4(partial_products_3_3_fu_240);
    eval_4_isog_mux_8dEe_U16->din5(partial_products_3_2_fu_244);
    eval_4_isog_mux_8dEe_U16->din6(partial_products_3_1_fu_248);
    eval_4_isog_mux_8dEe_U16->din7(partial_products_3_s_fu_252);
    eval_4_isog_mux_8dEe_U16->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U16->dout(tmp_5_fu_1479_p10);
    eval_4_isog_add_8eOg_U17 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U17");
    eval_4_isog_add_8eOg_U17->clk(ap_clk);
    eval_4_isog_add_8eOg_U17->reset(ap_rst);
    eval_4_isog_add_8eOg_U17->din0(grp_fu_1507_p0);
    eval_4_isog_add_8eOg_U17->din1(sum_V_3_0_reg_443);
    eval_4_isog_add_8eOg_U17->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U17->dout(grp_fu_1507_p2);
    eval_4_isog_mux_8dEe_U18 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U18");
    eval_4_isog_mux_8dEe_U18->din0(partial_products_7_11_fu_256);
    eval_4_isog_mux_8dEe_U18->din1(partial_products_4_6_fu_260);
    eval_4_isog_mux_8dEe_U18->din2(partial_products_4_5_fu_264);
    eval_4_isog_mux_8dEe_U18->din3(partial_products_4_4_fu_268);
    eval_4_isog_mux_8dEe_U18->din4(partial_products_4_3_fu_272);
    eval_4_isog_mux_8dEe_U18->din5(partial_products_4_2_fu_276);
    eval_4_isog_mux_8dEe_U18->din6(partial_products_4_1_fu_280);
    eval_4_isog_mux_8dEe_U18->din7(partial_products_4_s_fu_284);
    eval_4_isog_mux_8dEe_U18->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U18->dout(tmp_6_fu_1513_p10);
    eval_4_isog_add_8eOg_U19 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U19");
    eval_4_isog_add_8eOg_U19->clk(ap_clk);
    eval_4_isog_add_8eOg_U19->reset(ap_rst);
    eval_4_isog_add_8eOg_U19->din0(grp_fu_1541_p0);
    eval_4_isog_add_8eOg_U19->din1(sum_V_4_0_reg_455);
    eval_4_isog_add_8eOg_U19->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U19->dout(grp_fu_1541_p2);
    eval_4_isog_mux_8dEe_U20 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U20");
    eval_4_isog_mux_8dEe_U20->din0(partial_products_7_12_fu_288);
    eval_4_isog_mux_8dEe_U20->din1(partial_products_5_6_fu_292);
    eval_4_isog_mux_8dEe_U20->din2(partial_products_5_5_fu_296);
    eval_4_isog_mux_8dEe_U20->din3(partial_products_5_4_fu_300);
    eval_4_isog_mux_8dEe_U20->din4(partial_products_5_3_fu_304);
    eval_4_isog_mux_8dEe_U20->din5(partial_products_5_2_fu_308);
    eval_4_isog_mux_8dEe_U20->din6(partial_products_5_1_fu_312);
    eval_4_isog_mux_8dEe_U20->din7(partial_products_5_s_fu_316);
    eval_4_isog_mux_8dEe_U20->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U20->dout(tmp_7_fu_1547_p10);
    eval_4_isog_add_8eOg_U21 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U21");
    eval_4_isog_add_8eOg_U21->clk(ap_clk);
    eval_4_isog_add_8eOg_U21->reset(ap_rst);
    eval_4_isog_add_8eOg_U21->din0(grp_fu_1575_p0);
    eval_4_isog_add_8eOg_U21->din1(sum_V_5_0_reg_467);
    eval_4_isog_add_8eOg_U21->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U21->dout(grp_fu_1575_p2);
    eval_4_isog_mux_8dEe_U22 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U22");
    eval_4_isog_mux_8dEe_U22->din0(partial_products_7_13_fu_320);
    eval_4_isog_mux_8dEe_U22->din1(partial_products_6_6_fu_324);
    eval_4_isog_mux_8dEe_U22->din2(partial_products_6_5_fu_328);
    eval_4_isog_mux_8dEe_U22->din3(partial_products_6_4_fu_332);
    eval_4_isog_mux_8dEe_U22->din4(partial_products_6_3_fu_336);
    eval_4_isog_mux_8dEe_U22->din5(partial_products_6_2_fu_340);
    eval_4_isog_mux_8dEe_U22->din6(partial_products_6_1_fu_344);
    eval_4_isog_mux_8dEe_U22->din7(partial_products_6_s_fu_348);
    eval_4_isog_mux_8dEe_U22->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U22->dout(tmp_8_fu_1581_p10);
    eval_4_isog_add_8eOg_U23 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U23");
    eval_4_isog_add_8eOg_U23->clk(ap_clk);
    eval_4_isog_add_8eOg_U23->reset(ap_rst);
    eval_4_isog_add_8eOg_U23->din0(grp_fu_1609_p0);
    eval_4_isog_add_8eOg_U23->din1(sum_V_6_0_reg_479);
    eval_4_isog_add_8eOg_U23->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U23->dout(grp_fu_1609_p2);
    eval_4_isog_mux_8dEe_U24 = new eval_4_isog_mux_8dEe<1,1,896,896,896,896,896,896,896,896,3,896>("eval_4_isog_mux_8dEe_U24");
    eval_4_isog_mux_8dEe_U24->din0(partial_products_7_14_fu_352);
    eval_4_isog_mux_8dEe_U24->din1(partial_products_7_6_fu_356);
    eval_4_isog_mux_8dEe_U24->din2(partial_products_7_5_fu_360);
    eval_4_isog_mux_8dEe_U24->din3(partial_products_7_4_fu_364);
    eval_4_isog_mux_8dEe_U24->din4(partial_products_7_3_fu_368);
    eval_4_isog_mux_8dEe_U24->din5(partial_products_7_2_fu_372);
    eval_4_isog_mux_8dEe_U24->din6(partial_products_7_1_fu_376);
    eval_4_isog_mux_8dEe_U24->din7(partial_products_7_s_fu_380);
    eval_4_isog_mux_8dEe_U24->din8(trunc_ln44_fu_1379_p1);
    eval_4_isog_mux_8dEe_U24->dout(tmp_9_fu_1615_p10);
    eval_4_isog_add_8eOg_U25 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U25");
    eval_4_isog_add_8eOg_U25->clk(ap_clk);
    eval_4_isog_add_8eOg_U25->reset(ap_rst);
    eval_4_isog_add_8eOg_U25->din0(grp_fu_1643_p0);
    eval_4_isog_add_8eOg_U25->din1(sum_V_7_0_reg_491);
    eval_4_isog_add_8eOg_U25->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U25->dout(grp_fu_1643_p2);
    eval_4_isog_add_8eOg_U26 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U26");
    eval_4_isog_add_8eOg_U26->clk(ap_clk);
    eval_4_isog_add_8eOg_U26->reset(ap_rst);
    eval_4_isog_add_8eOg_U26->din0(sum_V_1_0_reg_419);
    eval_4_isog_add_8eOg_U26->din1(sum_V_0_0_reg_407);
    eval_4_isog_add_8eOg_U26->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U26->dout(grp_fu_1649_p2);
    eval_4_isog_add_8eOg_U27 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U27");
    eval_4_isog_add_8eOg_U27->clk(ap_clk);
    eval_4_isog_add_8eOg_U27->reset(ap_rst);
    eval_4_isog_add_8eOg_U27->din0(sum_V_2_0_reg_431);
    eval_4_isog_add_8eOg_U27->din1(sum_V_3_0_reg_443);
    eval_4_isog_add_8eOg_U27->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U27->dout(grp_fu_1655_p2);
    eval_4_isog_add_8eOg_U28 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U28");
    eval_4_isog_add_8eOg_U28->clk(ap_clk);
    eval_4_isog_add_8eOg_U28->reset(ap_rst);
    eval_4_isog_add_8eOg_U28->din0(sum_V_4_0_reg_455);
    eval_4_isog_add_8eOg_U28->din1(sum_V_5_0_reg_467);
    eval_4_isog_add_8eOg_U28->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U28->dout(grp_fu_1661_p2);
    eval_4_isog_add_8eOg_U29 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U29");
    eval_4_isog_add_8eOg_U29->clk(ap_clk);
    eval_4_isog_add_8eOg_U29->reset(ap_rst);
    eval_4_isog_add_8eOg_U29->din0(sum_V_6_0_reg_479);
    eval_4_isog_add_8eOg_U29->din1(sum_V_7_0_reg_491);
    eval_4_isog_add_8eOg_U29->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U29->dout(grp_fu_1667_p2);
    eval_4_isog_add_8eOg_U30 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U30");
    eval_4_isog_add_8eOg_U30->clk(ap_clk);
    eval_4_isog_add_8eOg_U30->reset(ap_rst);
    eval_4_isog_add_8eOg_U30->din0(grp_fu_1655_p2);
    eval_4_isog_add_8eOg_U30->din1(grp_fu_1649_p2);
    eval_4_isog_add_8eOg_U30->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U30->dout(grp_fu_1673_p2);
    eval_4_isog_add_8eOg_U31 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U31");
    eval_4_isog_add_8eOg_U31->clk(ap_clk);
    eval_4_isog_add_8eOg_U31->reset(ap_rst);
    eval_4_isog_add_8eOg_U31->din0(grp_fu_1667_p2);
    eval_4_isog_add_8eOg_U31->din1(grp_fu_1661_p2);
    eval_4_isog_add_8eOg_U31->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U31->dout(grp_fu_1679_p2);
    eval_4_isog_add_8eOg_U32 = new eval_4_isog_add_8eOg<1,2,896,896,896>("eval_4_isog_add_8eOg_U32");
    eval_4_isog_add_8eOg_U32->clk(ap_clk);
    eval_4_isog_add_8eOg_U32->reset(ap_rst);
    eval_4_isog_add_8eOg_U32->din0(grp_fu_1679_p2);
    eval_4_isog_add_8eOg_U32->din1(grp_fu_1673_p2);
    eval_4_isog_add_8eOg_U32->ce(ap_var_for_const0);
    eval_4_isog_add_8eOg_U32->dout(grp_fu_1685_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ai_0_V_fu_514_p1);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_1_V_fu_522_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_2_V_fu_542_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_3_V_fu_562_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_4_V_fu_582_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_5_V_fu_602_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_6_V_fu_622_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ai_7_V_fu_642_p4);
    sensitive << ( a_V );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln28_fu_694_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_bi_0_V_fu_518_p1);
    sensitive << ( b_V );

    SC_METHOD(thread_grp_fu_1439_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_3_fu_1411_p10 );

    SC_METHOD(thread_grp_fu_1473_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_4_fu_1445_p10 );

    SC_METHOD(thread_grp_fu_1507_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_5_fu_1479_p10 );

    SC_METHOD(thread_grp_fu_1541_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_6_fu_1513_p10 );

    SC_METHOD(thread_grp_fu_1575_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_7_fu_1547_p10 );

    SC_METHOD(thread_grp_fu_1609_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_8_fu_1581_p10 );

    SC_METHOD(thread_grp_fu_1643_p0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_9_fu_1615_p10 );

    SC_METHOD(thread_grp_fu_727_p0);
    sensitive << ( zext_ln215_reg_2115 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_727_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_732_p0);
    sensitive << ( zext_ln215_2_reg_2120 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_732_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_737_p0);
    sensitive << ( zext_ln215_3_reg_2125 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_737_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_742_p0);
    sensitive << ( zext_ln215_4_reg_2130 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_742_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_747_p0);
    sensitive << ( zext_ln215_5_reg_2135 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_747_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_752_p0);
    sensitive << ( zext_ln215_6_reg_2140 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_752_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_757_p0);
    sensitive << ( zext_ln215_7_reg_2145 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_757_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_762_p0);
    sensitive << ( zext_ln215_8_reg_2150 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_762_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( zext_ln215_1_fu_724_p1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_i_1_fu_700_p2);
    sensitive << ( i7_0_reg_396 );

    SC_METHOD(thread_i_fu_1181_p2);
    sensitive << ( i8_0_reg_503 );

    SC_METHOD(thread_icmp_ln28_fu_694_p2);
    sensitive << ( i7_0_reg_396 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln41_fu_1175_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i8_0_reg_503 );

    SC_METHOD(thread_partial_products_0_10_fu_795_p3);
    sensitive << ( grp_fu_742_p2 );

    SC_METHOD(thread_partial_products_0_11_fu_807_p3);
    sensitive << ( grp_fu_747_p2 );

    SC_METHOD(thread_partial_products_0_12_fu_819_p3);
    sensitive << ( grp_fu_752_p2 );

    SC_METHOD(thread_partial_products_0_13_fu_831_p3);
    sensitive << ( grp_fu_757_p2 );

    SC_METHOD(thread_partial_products_0_14_fu_843_p3);
    sensitive << ( grp_fu_762_p2 );

    SC_METHOD(thread_partial_products_0_7_fu_767_p1);
    sensitive << ( grp_fu_727_p2 );

    SC_METHOD(thread_partial_products_0_8_fu_771_p3);
    sensitive << ( grp_fu_732_p2 );

    SC_METHOD(thread_partial_products_0_9_fu_783_p3);
    sensitive << ( grp_fu_737_p2 );

    SC_METHOD(thread_tmp_1_fu_710_p9);
    sensitive << ( i7_0_reg_396 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_trunc_ln215_fu_706_p1);
    sensitive << ( i7_0_reg_396 );

    SC_METHOD(thread_trunc_ln44_fu_1379_p1);
    sensitive << ( i8_0_reg_503 );

    SC_METHOD(thread_zext_ln1503_1_fu_791_p1);
    sensitive << ( partial_products_0_9_fu_783_p3 );

    SC_METHOD(thread_zext_ln1503_2_fu_803_p1);
    sensitive << ( partial_products_0_10_fu_795_p3 );

    SC_METHOD(thread_zext_ln1503_3_fu_815_p1);
    sensitive << ( partial_products_0_11_fu_807_p3 );

    SC_METHOD(thread_zext_ln1503_4_fu_827_p1);
    sensitive << ( partial_products_0_12_fu_819_p3 );

    SC_METHOD(thread_zext_ln1503_5_fu_839_p1);
    sensitive << ( partial_products_0_13_fu_831_p3 );

    SC_METHOD(thread_zext_ln1503_6_fu_851_p1);
    sensitive << ( partial_products_0_14_fu_843_p3 );

    SC_METHOD(thread_zext_ln1503_fu_779_p1);
    sensitive << ( partial_products_0_8_fu_771_p3 );

    SC_METHOD(thread_zext_ln215_1_fu_724_p1);
    sensitive << ( tmp_1_reg_2168 );

    SC_METHOD(thread_zext_ln215_2_fu_666_p1);
    sensitive << ( ai_1_V_fu_522_p4 );

    SC_METHOD(thread_zext_ln215_3_fu_670_p1);
    sensitive << ( ai_2_V_fu_542_p4 );

    SC_METHOD(thread_zext_ln215_4_fu_674_p1);
    sensitive << ( ai_3_V_fu_562_p4 );

    SC_METHOD(thread_zext_ln215_5_fu_678_p1);
    sensitive << ( ai_4_V_fu_582_p4 );

    SC_METHOD(thread_zext_ln215_6_fu_682_p1);
    sensitive << ( ai_5_V_fu_602_p4 );

    SC_METHOD(thread_zext_ln215_7_fu_686_p1);
    sensitive << ( ai_6_V_fu_622_p4 );

    SC_METHOD(thread_zext_ln215_8_fu_690_p1);
    sensitive << ( ai_7_V_fu_642_p4 );

    SC_METHOD(thread_zext_ln215_fu_662_p1);
    sensitive << ( ai_0_V_fu_514_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( icmp_ln28_fu_694_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln41_fu_1175_p2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "00000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_return_preg = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "bc_mult_448_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_V, "(port)a_V");
    sc_trace(mVcdFile, b_V, "(port)b_V");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i7_0_reg_396, "i7_0_reg_396");
    sc_trace(mVcdFile, bi_0_V_fu_518_p1, "bi_0_V_fu_518_p1");
    sc_trace(mVcdFile, bi_0_V_reg_2075, "bi_0_V_reg_2075");
    sc_trace(mVcdFile, bi_1_V_reg_2080, "bi_1_V_reg_2080");
    sc_trace(mVcdFile, bi_2_V_reg_2085, "bi_2_V_reg_2085");
    sc_trace(mVcdFile, bi_3_V_reg_2090, "bi_3_V_reg_2090");
    sc_trace(mVcdFile, bi_4_V_reg_2095, "bi_4_V_reg_2095");
    sc_trace(mVcdFile, bi_5_V_reg_2100, "bi_5_V_reg_2100");
    sc_trace(mVcdFile, bi_6_V_reg_2105, "bi_6_V_reg_2105");
    sc_trace(mVcdFile, bi_7_V_reg_2110, "bi_7_V_reg_2110");
    sc_trace(mVcdFile, zext_ln215_fu_662_p1, "zext_ln215_fu_662_p1");
    sc_trace(mVcdFile, zext_ln215_reg_2115, "zext_ln215_reg_2115");
    sc_trace(mVcdFile, zext_ln215_2_fu_666_p1, "zext_ln215_2_fu_666_p1");
    sc_trace(mVcdFile, zext_ln215_2_reg_2120, "zext_ln215_2_reg_2120");
    sc_trace(mVcdFile, zext_ln215_3_fu_670_p1, "zext_ln215_3_fu_670_p1");
    sc_trace(mVcdFile, zext_ln215_3_reg_2125, "zext_ln215_3_reg_2125");
    sc_trace(mVcdFile, zext_ln215_4_fu_674_p1, "zext_ln215_4_fu_674_p1");
    sc_trace(mVcdFile, zext_ln215_4_reg_2130, "zext_ln215_4_reg_2130");
    sc_trace(mVcdFile, zext_ln215_5_fu_678_p1, "zext_ln215_5_fu_678_p1");
    sc_trace(mVcdFile, zext_ln215_5_reg_2135, "zext_ln215_5_reg_2135");
    sc_trace(mVcdFile, zext_ln215_6_fu_682_p1, "zext_ln215_6_fu_682_p1");
    sc_trace(mVcdFile, zext_ln215_6_reg_2140, "zext_ln215_6_reg_2140");
    sc_trace(mVcdFile, zext_ln215_7_fu_686_p1, "zext_ln215_7_fu_686_p1");
    sc_trace(mVcdFile, zext_ln215_7_reg_2145, "zext_ln215_7_reg_2145");
    sc_trace(mVcdFile, zext_ln215_8_fu_690_p1, "zext_ln215_8_fu_690_p1");
    sc_trace(mVcdFile, zext_ln215_8_reg_2150, "zext_ln215_8_reg_2150");
    sc_trace(mVcdFile, icmp_ln28_fu_694_p2, "icmp_ln28_fu_694_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_1_fu_700_p2, "i_1_fu_700_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, trunc_ln215_fu_706_p1, "trunc_ln215_fu_706_p1");
    sc_trace(mVcdFile, trunc_ln215_reg_2164, "trunc_ln215_reg_2164");
    sc_trace(mVcdFile, trunc_ln215_reg_2164_pp0_iter1_reg, "trunc_ln215_reg_2164_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_1_fu_710_p10, "tmp_1_fu_710_p10");
    sc_trace(mVcdFile, tmp_1_reg_2168, "tmp_1_reg_2168");
    sc_trace(mVcdFile, zext_ln215_1_fu_724_p1, "zext_ln215_1_fu_724_p1");
    sc_trace(mVcdFile, i_fu_1181_p2, "i_fu_1181_p2");
    sc_trace(mVcdFile, i_reg_2188, "i_reg_2188");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_2_fu_1383_p10, "tmp_2_fu_1383_p10");
    sc_trace(mVcdFile, icmp_ln41_fu_1175_p2, "icmp_ln41_fu_1175_p2");
    sc_trace(mVcdFile, grp_fu_1405_p2, "grp_fu_1405_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_1439_p2, "grp_fu_1439_p2");
    sc_trace(mVcdFile, grp_fu_1473_p2, "grp_fu_1473_p2");
    sc_trace(mVcdFile, grp_fu_1507_p2, "grp_fu_1507_p2");
    sc_trace(mVcdFile, grp_fu_1541_p2, "grp_fu_1541_p2");
    sc_trace(mVcdFile, grp_fu_1575_p2, "grp_fu_1575_p2");
    sc_trace(mVcdFile, grp_fu_1609_p2, "grp_fu_1609_p2");
    sc_trace(mVcdFile, grp_fu_1643_p2, "grp_fu_1643_p2");
    sc_trace(mVcdFile, grp_fu_1649_p2, "grp_fu_1649_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_1655_p2, "grp_fu_1655_p2");
    sc_trace(mVcdFile, grp_fu_1661_p2, "grp_fu_1661_p2");
    sc_trace(mVcdFile, grp_fu_1667_p2, "grp_fu_1667_p2");
    sc_trace(mVcdFile, grp_fu_1673_p2, "grp_fu_1673_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, grp_fu_1679_p2, "grp_fu_1679_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, sum_V_0_0_reg_407, "sum_V_0_0_reg_407");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, sum_V_1_0_reg_419, "sum_V_1_0_reg_419");
    sc_trace(mVcdFile, sum_V_2_0_reg_431, "sum_V_2_0_reg_431");
    sc_trace(mVcdFile, sum_V_3_0_reg_443, "sum_V_3_0_reg_443");
    sc_trace(mVcdFile, sum_V_4_0_reg_455, "sum_V_4_0_reg_455");
    sc_trace(mVcdFile, sum_V_5_0_reg_467, "sum_V_5_0_reg_467");
    sc_trace(mVcdFile, sum_V_6_0_reg_479, "sum_V_6_0_reg_479");
    sc_trace(mVcdFile, sum_V_7_0_reg_491, "sum_V_7_0_reg_491");
    sc_trace(mVcdFile, i8_0_reg_503, "i8_0_reg_503");
    sc_trace(mVcdFile, partial_products_7_7_fu_128, "partial_products_7_7_fu_128");
    sc_trace(mVcdFile, partial_products_0_7_fu_767_p1, "partial_products_0_7_fu_767_p1");
    sc_trace(mVcdFile, partial_products_0_6_fu_132, "partial_products_0_6_fu_132");
    sc_trace(mVcdFile, zext_ln1503_fu_779_p1, "zext_ln1503_fu_779_p1");
    sc_trace(mVcdFile, partial_products_0_5_fu_136, "partial_products_0_5_fu_136");
    sc_trace(mVcdFile, zext_ln1503_1_fu_791_p1, "zext_ln1503_1_fu_791_p1");
    sc_trace(mVcdFile, partial_products_0_4_fu_140, "partial_products_0_4_fu_140");
    sc_trace(mVcdFile, zext_ln1503_2_fu_803_p1, "zext_ln1503_2_fu_803_p1");
    sc_trace(mVcdFile, partial_products_0_3_fu_144, "partial_products_0_3_fu_144");
    sc_trace(mVcdFile, zext_ln1503_3_fu_815_p1, "zext_ln1503_3_fu_815_p1");
    sc_trace(mVcdFile, partial_products_0_2_fu_148, "partial_products_0_2_fu_148");
    sc_trace(mVcdFile, zext_ln1503_4_fu_827_p1, "zext_ln1503_4_fu_827_p1");
    sc_trace(mVcdFile, partial_products_0_1_fu_152, "partial_products_0_1_fu_152");
    sc_trace(mVcdFile, zext_ln1503_5_fu_839_p1, "zext_ln1503_5_fu_839_p1");
    sc_trace(mVcdFile, partial_products_0_s_fu_156, "partial_products_0_s_fu_156");
    sc_trace(mVcdFile, zext_ln1503_6_fu_851_p1, "zext_ln1503_6_fu_851_p1");
    sc_trace(mVcdFile, partial_products_7_8_fu_160, "partial_products_7_8_fu_160");
    sc_trace(mVcdFile, partial_products_1_6_fu_164, "partial_products_1_6_fu_164");
    sc_trace(mVcdFile, partial_products_1_5_fu_168, "partial_products_1_5_fu_168");
    sc_trace(mVcdFile, partial_products_1_4_fu_172, "partial_products_1_4_fu_172");
    sc_trace(mVcdFile, partial_products_1_3_fu_176, "partial_products_1_3_fu_176");
    sc_trace(mVcdFile, partial_products_1_2_fu_180, "partial_products_1_2_fu_180");
    sc_trace(mVcdFile, partial_products_1_1_fu_184, "partial_products_1_1_fu_184");
    sc_trace(mVcdFile, partial_products_1_s_fu_188, "partial_products_1_s_fu_188");
    sc_trace(mVcdFile, partial_products_7_9_fu_192, "partial_products_7_9_fu_192");
    sc_trace(mVcdFile, partial_products_2_6_fu_196, "partial_products_2_6_fu_196");
    sc_trace(mVcdFile, partial_products_2_5_fu_200, "partial_products_2_5_fu_200");
    sc_trace(mVcdFile, partial_products_2_4_fu_204, "partial_products_2_4_fu_204");
    sc_trace(mVcdFile, partial_products_2_3_fu_208, "partial_products_2_3_fu_208");
    sc_trace(mVcdFile, partial_products_2_2_fu_212, "partial_products_2_2_fu_212");
    sc_trace(mVcdFile, partial_products_2_1_fu_216, "partial_products_2_1_fu_216");
    sc_trace(mVcdFile, partial_products_2_s_fu_220, "partial_products_2_s_fu_220");
    sc_trace(mVcdFile, partial_products_7_10_fu_224, "partial_products_7_10_fu_224");
    sc_trace(mVcdFile, partial_products_3_6_fu_228, "partial_products_3_6_fu_228");
    sc_trace(mVcdFile, partial_products_3_5_fu_232, "partial_products_3_5_fu_232");
    sc_trace(mVcdFile, partial_products_3_4_fu_236, "partial_products_3_4_fu_236");
    sc_trace(mVcdFile, partial_products_3_3_fu_240, "partial_products_3_3_fu_240");
    sc_trace(mVcdFile, partial_products_3_2_fu_244, "partial_products_3_2_fu_244");
    sc_trace(mVcdFile, partial_products_3_1_fu_248, "partial_products_3_1_fu_248");
    sc_trace(mVcdFile, partial_products_3_s_fu_252, "partial_products_3_s_fu_252");
    sc_trace(mVcdFile, partial_products_7_11_fu_256, "partial_products_7_11_fu_256");
    sc_trace(mVcdFile, partial_products_4_6_fu_260, "partial_products_4_6_fu_260");
    sc_trace(mVcdFile, partial_products_4_5_fu_264, "partial_products_4_5_fu_264");
    sc_trace(mVcdFile, partial_products_4_4_fu_268, "partial_products_4_4_fu_268");
    sc_trace(mVcdFile, partial_products_4_3_fu_272, "partial_products_4_3_fu_272");
    sc_trace(mVcdFile, partial_products_4_2_fu_276, "partial_products_4_2_fu_276");
    sc_trace(mVcdFile, partial_products_4_1_fu_280, "partial_products_4_1_fu_280");
    sc_trace(mVcdFile, partial_products_4_s_fu_284, "partial_products_4_s_fu_284");
    sc_trace(mVcdFile, partial_products_7_12_fu_288, "partial_products_7_12_fu_288");
    sc_trace(mVcdFile, partial_products_5_6_fu_292, "partial_products_5_6_fu_292");
    sc_trace(mVcdFile, partial_products_5_5_fu_296, "partial_products_5_5_fu_296");
    sc_trace(mVcdFile, partial_products_5_4_fu_300, "partial_products_5_4_fu_300");
    sc_trace(mVcdFile, partial_products_5_3_fu_304, "partial_products_5_3_fu_304");
    sc_trace(mVcdFile, partial_products_5_2_fu_308, "partial_products_5_2_fu_308");
    sc_trace(mVcdFile, partial_products_5_1_fu_312, "partial_products_5_1_fu_312");
    sc_trace(mVcdFile, partial_products_5_s_fu_316, "partial_products_5_s_fu_316");
    sc_trace(mVcdFile, partial_products_7_13_fu_320, "partial_products_7_13_fu_320");
    sc_trace(mVcdFile, partial_products_6_6_fu_324, "partial_products_6_6_fu_324");
    sc_trace(mVcdFile, partial_products_6_5_fu_328, "partial_products_6_5_fu_328");
    sc_trace(mVcdFile, partial_products_6_4_fu_332, "partial_products_6_4_fu_332");
    sc_trace(mVcdFile, partial_products_6_3_fu_336, "partial_products_6_3_fu_336");
    sc_trace(mVcdFile, partial_products_6_2_fu_340, "partial_products_6_2_fu_340");
    sc_trace(mVcdFile, partial_products_6_1_fu_344, "partial_products_6_1_fu_344");
    sc_trace(mVcdFile, partial_products_6_s_fu_348, "partial_products_6_s_fu_348");
    sc_trace(mVcdFile, partial_products_7_14_fu_352, "partial_products_7_14_fu_352");
    sc_trace(mVcdFile, partial_products_7_6_fu_356, "partial_products_7_6_fu_356");
    sc_trace(mVcdFile, partial_products_7_5_fu_360, "partial_products_7_5_fu_360");
    sc_trace(mVcdFile, partial_products_7_4_fu_364, "partial_products_7_4_fu_364");
    sc_trace(mVcdFile, partial_products_7_3_fu_368, "partial_products_7_3_fu_368");
    sc_trace(mVcdFile, partial_products_7_2_fu_372, "partial_products_7_2_fu_372");
    sc_trace(mVcdFile, partial_products_7_1_fu_376, "partial_products_7_1_fu_376");
    sc_trace(mVcdFile, partial_products_7_s_fu_380, "partial_products_7_s_fu_380");
    sc_trace(mVcdFile, ai_0_V_fu_514_p1, "ai_0_V_fu_514_p1");
    sc_trace(mVcdFile, ai_1_V_fu_522_p4, "ai_1_V_fu_522_p4");
    sc_trace(mVcdFile, ai_2_V_fu_542_p4, "ai_2_V_fu_542_p4");
    sc_trace(mVcdFile, ai_3_V_fu_562_p4, "ai_3_V_fu_562_p4");
    sc_trace(mVcdFile, ai_4_V_fu_582_p4, "ai_4_V_fu_582_p4");
    sc_trace(mVcdFile, ai_5_V_fu_602_p4, "ai_5_V_fu_602_p4");
    sc_trace(mVcdFile, ai_6_V_fu_622_p4, "ai_6_V_fu_622_p4");
    sc_trace(mVcdFile, ai_7_V_fu_642_p4, "ai_7_V_fu_642_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_1_fu_710_p9, "tmp_1_fu_710_p9");
    sc_trace(mVcdFile, grp_fu_727_p0, "grp_fu_727_p0");
    sc_trace(mVcdFile, grp_fu_727_p1, "grp_fu_727_p1");
    sc_trace(mVcdFile, grp_fu_732_p0, "grp_fu_732_p0");
    sc_trace(mVcdFile, grp_fu_732_p1, "grp_fu_732_p1");
    sc_trace(mVcdFile, grp_fu_737_p0, "grp_fu_737_p0");
    sc_trace(mVcdFile, grp_fu_737_p1, "grp_fu_737_p1");
    sc_trace(mVcdFile, grp_fu_742_p0, "grp_fu_742_p0");
    sc_trace(mVcdFile, grp_fu_742_p1, "grp_fu_742_p1");
    sc_trace(mVcdFile, grp_fu_747_p0, "grp_fu_747_p0");
    sc_trace(mVcdFile, grp_fu_747_p1, "grp_fu_747_p1");
    sc_trace(mVcdFile, grp_fu_752_p0, "grp_fu_752_p0");
    sc_trace(mVcdFile, grp_fu_752_p1, "grp_fu_752_p1");
    sc_trace(mVcdFile, grp_fu_757_p0, "grp_fu_757_p0");
    sc_trace(mVcdFile, grp_fu_757_p1, "grp_fu_757_p1");
    sc_trace(mVcdFile, grp_fu_762_p0, "grp_fu_762_p0");
    sc_trace(mVcdFile, grp_fu_762_p1, "grp_fu_762_p1");
    sc_trace(mVcdFile, grp_fu_727_p2, "grp_fu_727_p2");
    sc_trace(mVcdFile, grp_fu_732_p2, "grp_fu_732_p2");
    sc_trace(mVcdFile, partial_products_0_8_fu_771_p3, "partial_products_0_8_fu_771_p3");
    sc_trace(mVcdFile, grp_fu_737_p2, "grp_fu_737_p2");
    sc_trace(mVcdFile, partial_products_0_9_fu_783_p3, "partial_products_0_9_fu_783_p3");
    sc_trace(mVcdFile, grp_fu_742_p2, "grp_fu_742_p2");
    sc_trace(mVcdFile, partial_products_0_10_fu_795_p3, "partial_products_0_10_fu_795_p3");
    sc_trace(mVcdFile, grp_fu_747_p2, "grp_fu_747_p2");
    sc_trace(mVcdFile, partial_products_0_11_fu_807_p3, "partial_products_0_11_fu_807_p3");
    sc_trace(mVcdFile, grp_fu_752_p2, "grp_fu_752_p2");
    sc_trace(mVcdFile, partial_products_0_12_fu_819_p3, "partial_products_0_12_fu_819_p3");
    sc_trace(mVcdFile, grp_fu_757_p2, "grp_fu_757_p2");
    sc_trace(mVcdFile, partial_products_0_13_fu_831_p3, "partial_products_0_13_fu_831_p3");
    sc_trace(mVcdFile, grp_fu_762_p2, "grp_fu_762_p2");
    sc_trace(mVcdFile, partial_products_0_14_fu_843_p3, "partial_products_0_14_fu_843_p3");
    sc_trace(mVcdFile, trunc_ln44_fu_1379_p1, "trunc_ln44_fu_1379_p1");
    sc_trace(mVcdFile, tmp_3_fu_1411_p10, "tmp_3_fu_1411_p10");
    sc_trace(mVcdFile, grp_fu_1439_p0, "grp_fu_1439_p0");
    sc_trace(mVcdFile, tmp_4_fu_1445_p10, "tmp_4_fu_1445_p10");
    sc_trace(mVcdFile, grp_fu_1473_p0, "grp_fu_1473_p0");
    sc_trace(mVcdFile, tmp_5_fu_1479_p10, "tmp_5_fu_1479_p10");
    sc_trace(mVcdFile, grp_fu_1507_p0, "grp_fu_1507_p0");
    sc_trace(mVcdFile, tmp_6_fu_1513_p10, "tmp_6_fu_1513_p10");
    sc_trace(mVcdFile, grp_fu_1541_p0, "grp_fu_1541_p0");
    sc_trace(mVcdFile, tmp_7_fu_1547_p10, "tmp_7_fu_1547_p10");
    sc_trace(mVcdFile, grp_fu_1575_p0, "grp_fu_1575_p0");
    sc_trace(mVcdFile, tmp_8_fu_1581_p10, "tmp_8_fu_1581_p10");
    sc_trace(mVcdFile, grp_fu_1609_p0, "grp_fu_1609_p0");
    sc_trace(mVcdFile, tmp_9_fu_1615_p10, "tmp_9_fu_1615_p10");
    sc_trace(mVcdFile, grp_fu_1643_p0, "grp_fu_1643_p0");
    sc_trace(mVcdFile, grp_fu_1685_p2, "grp_fu_1685_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

bc_mult_448::~bc_mult_448() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete eval_4_isog_mux_8bkb_U1;
    delete eval_4_isog_mul_5cud_U2;
    delete eval_4_isog_mul_5cud_U3;
    delete eval_4_isog_mul_5cud_U4;
    delete eval_4_isog_mul_5cud_U5;
    delete eval_4_isog_mul_5cud_U6;
    delete eval_4_isog_mul_5cud_U7;
    delete eval_4_isog_mul_5cud_U8;
    delete eval_4_isog_mul_5cud_U9;
    delete eval_4_isog_mux_8dEe_U10;
    delete eval_4_isog_add_8eOg_U11;
    delete eval_4_isog_mux_8dEe_U12;
    delete eval_4_isog_add_8eOg_U13;
    delete eval_4_isog_mux_8dEe_U14;
    delete eval_4_isog_add_8eOg_U15;
    delete eval_4_isog_mux_8dEe_U16;
    delete eval_4_isog_add_8eOg_U17;
    delete eval_4_isog_mux_8dEe_U18;
    delete eval_4_isog_add_8eOg_U19;
    delete eval_4_isog_mux_8dEe_U20;
    delete eval_4_isog_add_8eOg_U21;
    delete eval_4_isog_mux_8dEe_U22;
    delete eval_4_isog_add_8eOg_U23;
    delete eval_4_isog_mux_8dEe_U24;
    delete eval_4_isog_add_8eOg_U25;
    delete eval_4_isog_add_8eOg_U26;
    delete eval_4_isog_add_8eOg_U27;
    delete eval_4_isog_add_8eOg_U28;
    delete eval_4_isog_add_8eOg_U29;
    delete eval_4_isog_add_8eOg_U30;
    delete eval_4_isog_add_8eOg_U31;
    delete eval_4_isog_add_8eOg_U32;
}

void bc_mult_448::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void bc_mult_448::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv896_lc_1;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
            ap_return_preg = grp_fu_1685_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln28_fu_694_p2.read(), ap_const_lv1_0))) {
        i7_0_reg_396 = i_1_fu_700_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i7_0_reg_396 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i8_0_reg_503 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i8_0_reg_503 = i_reg_2188.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_0_0_reg_407 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_0_0_reg_407 = grp_fu_1405_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_1_0_reg_419 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_1_0_reg_419 = grp_fu_1439_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_2_0_reg_431 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_2_0_reg_431 = grp_fu_1473_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_3_0_reg_443 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_3_0_reg_443 = grp_fu_1507_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_4_0_reg_455 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_4_0_reg_455 = grp_fu_1541_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_5_0_reg_467 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_5_0_reg_467 = grp_fu_1575_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_6_0_reg_479 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_6_0_reg_479 = grp_fu_1609_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        sum_V_7_0_reg_491 = ap_const_lv896_lc_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        sum_V_7_0_reg_491 = grp_fu_1643_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ap_return = grp_fu_1685_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        bi_0_V_reg_2075 = bi_0_V_fu_518_p1.read();
        bi_1_V_reg_2080 = b_V.read().range(111, 56);
        bi_2_V_reg_2085 = b_V.read().range(167, 112);
        bi_3_V_reg_2090 = b_V.read().range(223, 168);
        bi_4_V_reg_2095 = b_V.read().range(279, 224);
        bi_5_V_reg_2100 = b_V.read().range(335, 280);
        bi_6_V_reg_2105 = b_V.read().range(391, 336);
        bi_7_V_reg_2110 = b_V.read().range(447, 392);
        zext_ln215_2_reg_2120 = zext_ln215_2_fu_666_p1.read();
        zext_ln215_3_reg_2125 = zext_ln215_3_fu_670_p1.read();
        zext_ln215_4_reg_2130 = zext_ln215_4_fu_674_p1.read();
        zext_ln215_5_reg_2135 = zext_ln215_5_fu_678_p1.read();
        zext_ln215_6_reg_2140 = zext_ln215_6_fu_682_p1.read();
        zext_ln215_7_reg_2145 = zext_ln215_7_fu_686_p1.read();
        zext_ln215_8_reg_2150 = zext_ln215_8_fu_690_p1.read();
        zext_ln215_reg_2115 = zext_ln215_fu_662_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_reg_2188 = i_fu_1181_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_0))) {
        partial_products_0_1_fu_152 = zext_ln1503_5_fu_839_p1.read();
        partial_products_0_2_fu_148 = zext_ln1503_4_fu_827_p1.read();
        partial_products_0_3_fu_144 = zext_ln1503_3_fu_815_p1.read();
        partial_products_0_4_fu_140 = zext_ln1503_2_fu_803_p1.read();
        partial_products_0_5_fu_136 = zext_ln1503_1_fu_791_p1.read();
        partial_products_0_6_fu_132 = zext_ln1503_fu_779_p1.read();
        partial_products_0_s_fu_156 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_7_fu_128 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_1))) {
        partial_products_1_1_fu_184 = zext_ln1503_5_fu_839_p1.read();
        partial_products_1_2_fu_180 = zext_ln1503_4_fu_827_p1.read();
        partial_products_1_3_fu_176 = zext_ln1503_3_fu_815_p1.read();
        partial_products_1_4_fu_172 = zext_ln1503_2_fu_803_p1.read();
        partial_products_1_5_fu_168 = zext_ln1503_1_fu_791_p1.read();
        partial_products_1_6_fu_164 = zext_ln1503_fu_779_p1.read();
        partial_products_1_s_fu_188 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_8_fu_160 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_2))) {
        partial_products_2_1_fu_216 = zext_ln1503_5_fu_839_p1.read();
        partial_products_2_2_fu_212 = zext_ln1503_4_fu_827_p1.read();
        partial_products_2_3_fu_208 = zext_ln1503_3_fu_815_p1.read();
        partial_products_2_4_fu_204 = zext_ln1503_2_fu_803_p1.read();
        partial_products_2_5_fu_200 = zext_ln1503_1_fu_791_p1.read();
        partial_products_2_6_fu_196 = zext_ln1503_fu_779_p1.read();
        partial_products_2_s_fu_220 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_9_fu_192 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_3))) {
        partial_products_3_1_fu_248 = zext_ln1503_5_fu_839_p1.read();
        partial_products_3_2_fu_244 = zext_ln1503_4_fu_827_p1.read();
        partial_products_3_3_fu_240 = zext_ln1503_3_fu_815_p1.read();
        partial_products_3_4_fu_236 = zext_ln1503_2_fu_803_p1.read();
        partial_products_3_5_fu_232 = zext_ln1503_1_fu_791_p1.read();
        partial_products_3_6_fu_228 = zext_ln1503_fu_779_p1.read();
        partial_products_3_s_fu_252 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_10_fu_224 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_4))) {
        partial_products_4_1_fu_280 = zext_ln1503_5_fu_839_p1.read();
        partial_products_4_2_fu_276 = zext_ln1503_4_fu_827_p1.read();
        partial_products_4_3_fu_272 = zext_ln1503_3_fu_815_p1.read();
        partial_products_4_4_fu_268 = zext_ln1503_2_fu_803_p1.read();
        partial_products_4_5_fu_264 = zext_ln1503_1_fu_791_p1.read();
        partial_products_4_6_fu_260 = zext_ln1503_fu_779_p1.read();
        partial_products_4_s_fu_284 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_11_fu_256 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_5))) {
        partial_products_5_1_fu_312 = zext_ln1503_5_fu_839_p1.read();
        partial_products_5_2_fu_308 = zext_ln1503_4_fu_827_p1.read();
        partial_products_5_3_fu_304 = zext_ln1503_3_fu_815_p1.read();
        partial_products_5_4_fu_300 = zext_ln1503_2_fu_803_p1.read();
        partial_products_5_5_fu_296 = zext_ln1503_1_fu_791_p1.read();
        partial_products_5_6_fu_292 = zext_ln1503_fu_779_p1.read();
        partial_products_5_s_fu_316 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_12_fu_288 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_6))) {
        partial_products_6_1_fu_344 = zext_ln1503_5_fu_839_p1.read();
        partial_products_6_2_fu_340 = zext_ln1503_4_fu_827_p1.read();
        partial_products_6_3_fu_336 = zext_ln1503_3_fu_815_p1.read();
        partial_products_6_4_fu_332 = zext_ln1503_2_fu_803_p1.read();
        partial_products_6_5_fu_328 = zext_ln1503_1_fu_791_p1.read();
        partial_products_6_6_fu_324 = zext_ln1503_fu_779_p1.read();
        partial_products_6_s_fu_348 = zext_ln1503_6_fu_851_p1.read();
        partial_products_7_13_fu_320 = partial_products_0_7_fu_767_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,3,3>(trunc_ln215_reg_2164_pp0_iter1_reg.read(), ap_const_lv3_7))) {
        partial_products_7_14_fu_352 = partial_products_0_7_fu_767_p1.read();
        partial_products_7_1_fu_376 = zext_ln1503_5_fu_839_p1.read();
        partial_products_7_2_fu_372 = zext_ln1503_4_fu_827_p1.read();
        partial_products_7_3_fu_368 = zext_ln1503_3_fu_815_p1.read();
        partial_products_7_4_fu_364 = zext_ln1503_2_fu_803_p1.read();
        partial_products_7_5_fu_360 = zext_ln1503_1_fu_791_p1.read();
        partial_products_7_6_fu_356 = zext_ln1503_fu_779_p1.read();
        partial_products_7_s_fu_380 = zext_ln1503_6_fu_851_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln28_fu_694_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_2168 = tmp_1_fu_710_p10.read();
        trunc_ln215_reg_2164 = trunc_ln215_fu_706_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        trunc_ln215_reg_2164_pp0_iter1_reg = trunc_ln215_reg_2164.read();
    }
}

void bc_mult_448::thread_ai_0_V_fu_514_p1() {
    ai_0_V_fu_514_p1 = a_V.read().range(56-1, 0);
}

void bc_mult_448::thread_ai_1_V_fu_522_p4() {
    ai_1_V_fu_522_p4 = a_V.read().range(111, 56);
}

void bc_mult_448::thread_ai_2_V_fu_542_p4() {
    ai_2_V_fu_542_p4 = a_V.read().range(167, 112);
}

void bc_mult_448::thread_ai_3_V_fu_562_p4() {
    ai_3_V_fu_562_p4 = a_V.read().range(223, 168);
}

void bc_mult_448::thread_ai_4_V_fu_582_p4() {
    ai_4_V_fu_582_p4 = a_V.read().range(279, 224);
}

void bc_mult_448::thread_ai_5_V_fu_602_p4() {
    ai_5_V_fu_602_p4 = a_V.read().range(335, 280);
}

void bc_mult_448::thread_ai_6_V_fu_622_p4() {
    ai_6_V_fu_622_p4 = a_V.read().range(391, 336);
}

void bc_mult_448::thread_ai_7_V_fu_642_p4() {
    ai_7_V_fu_642_p4 = a_V.read().range(447, 392);
}

void bc_mult_448::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void bc_mult_448::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void bc_mult_448::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[7];
}

void bc_mult_448::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[2];
}

void bc_mult_448::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[3];
}

void bc_mult_448::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[4];
}

void bc_mult_448::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[5];
}

void bc_mult_448::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[6];
}

void bc_mult_448::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void bc_mult_448::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void bc_mult_448::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void bc_mult_448::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void bc_mult_448::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void bc_mult_448::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void bc_mult_448::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln28_fu_694_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void bc_mult_448::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void bc_mult_448::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void bc_mult_448::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void bc_mult_448::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void bc_mult_448::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void bc_mult_448::thread_bi_0_V_fu_518_p1() {
    bi_0_V_fu_518_p1 = b_V.read().range(56-1, 0);
}

void bc_mult_448::thread_grp_fu_1439_p0() {
    grp_fu_1439_p0 = (!ap_const_lv896_lc_2.is_01())? sc_lv<896>(): tmp_3_fu_1411_p10.read() << (unsigned short)ap_const_lv896_lc_2.to_uint();
}

void bc_mult_448::thread_grp_fu_1473_p0() {
    grp_fu_1473_p0 = (!ap_const_lv896_lc_3.is_01())? sc_lv<896>(): tmp_4_fu_1445_p10.read() << (unsigned short)ap_const_lv896_lc_3.to_uint();
}

void bc_mult_448::thread_grp_fu_1507_p0() {
    grp_fu_1507_p0 = (!ap_const_lv896_lc_4.is_01())? sc_lv<896>(): tmp_5_fu_1479_p10.read() << (unsigned short)ap_const_lv896_lc_4.to_uint();
}

void bc_mult_448::thread_grp_fu_1541_p0() {
    grp_fu_1541_p0 = (!ap_const_lv896_lc_5.is_01())? sc_lv<896>(): tmp_6_fu_1513_p10.read() << (unsigned short)ap_const_lv896_lc_5.to_uint();
}

void bc_mult_448::thread_grp_fu_1575_p0() {
    grp_fu_1575_p0 = (!ap_const_lv896_lc_6.is_01())? sc_lv<896>(): tmp_7_fu_1547_p10.read() << (unsigned short)ap_const_lv896_lc_6.to_uint();
}

void bc_mult_448::thread_grp_fu_1609_p0() {
    grp_fu_1609_p0 = (!ap_const_lv896_lc_7.is_01())? sc_lv<896>(): tmp_8_fu_1581_p10.read() << (unsigned short)ap_const_lv896_lc_7.to_uint();
}

void bc_mult_448::thread_grp_fu_1643_p0() {
    grp_fu_1643_p0 = (!ap_const_lv896_lc_8.is_01())? sc_lv<896>(): tmp_9_fu_1615_p10.read() << (unsigned short)ap_const_lv896_lc_8.to_uint();
}

void bc_mult_448::thread_grp_fu_727_p0() {
    grp_fu_727_p0 =  (sc_lv<56>) (zext_ln215_reg_2115.read());
}

void bc_mult_448::thread_grp_fu_727_p1() {
    grp_fu_727_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_732_p0() {
    grp_fu_732_p0 =  (sc_lv<56>) (zext_ln215_2_reg_2120.read());
}

void bc_mult_448::thread_grp_fu_732_p1() {
    grp_fu_732_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_737_p0() {
    grp_fu_737_p0 =  (sc_lv<56>) (zext_ln215_3_reg_2125.read());
}

void bc_mult_448::thread_grp_fu_737_p1() {
    grp_fu_737_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_742_p0() {
    grp_fu_742_p0 =  (sc_lv<56>) (zext_ln215_4_reg_2130.read());
}

void bc_mult_448::thread_grp_fu_742_p1() {
    grp_fu_742_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_747_p0() {
    grp_fu_747_p0 =  (sc_lv<56>) (zext_ln215_5_reg_2135.read());
}

void bc_mult_448::thread_grp_fu_747_p1() {
    grp_fu_747_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_752_p0() {
    grp_fu_752_p0 =  (sc_lv<56>) (zext_ln215_6_reg_2140.read());
}

void bc_mult_448::thread_grp_fu_752_p1() {
    grp_fu_752_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_757_p0() {
    grp_fu_757_p0 =  (sc_lv<56>) (zext_ln215_7_reg_2145.read());
}

void bc_mult_448::thread_grp_fu_757_p1() {
    grp_fu_757_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_grp_fu_762_p0() {
    grp_fu_762_p0 =  (sc_lv<56>) (zext_ln215_8_reg_2150.read());
}

void bc_mult_448::thread_grp_fu_762_p1() {
    grp_fu_762_p1 =  (sc_lv<56>) (zext_ln215_1_fu_724_p1.read());
}

void bc_mult_448::thread_i_1_fu_700_p2() {
    i_1_fu_700_p2 = (!i7_0_reg_396.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i7_0_reg_396.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void bc_mult_448::thread_i_fu_1181_p2() {
    i_fu_1181_p2 = (!i8_0_reg_503.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i8_0_reg_503.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void bc_mult_448::thread_icmp_ln28_fu_694_p2() {
    icmp_ln28_fu_694_p2 = (!i7_0_reg_396.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i7_0_reg_396.read() == ap_const_lv4_8);
}

void bc_mult_448::thread_icmp_ln41_fu_1175_p2() {
    icmp_ln41_fu_1175_p2 = (!i8_0_reg_503.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i8_0_reg_503.read() == ap_const_lv4_8);
}

void bc_mult_448::thread_partial_products_0_10_fu_795_p3() {
    partial_products_0_10_fu_795_p3 = esl_concat<112,168>(grp_fu_742_p2.read(), ap_const_lv168_lc_1);
}

void bc_mult_448::thread_partial_products_0_11_fu_807_p3() {
    partial_products_0_11_fu_807_p3 = esl_concat<112,224>(grp_fu_747_p2.read(), ap_const_lv224_lc_1);
}

void bc_mult_448::thread_partial_products_0_12_fu_819_p3() {
    partial_products_0_12_fu_819_p3 = esl_concat<112,280>(grp_fu_752_p2.read(), ap_const_lv280_lc_1);
}

void bc_mult_448::thread_partial_products_0_13_fu_831_p3() {
    partial_products_0_13_fu_831_p3 = esl_concat<112,336>(grp_fu_757_p2.read(), ap_const_lv336_lc_1);
}

void bc_mult_448::thread_partial_products_0_14_fu_843_p3() {
    partial_products_0_14_fu_843_p3 = esl_concat<112,392>(grp_fu_762_p2.read(), ap_const_lv392_lc_1);
}

void bc_mult_448::thread_partial_products_0_7_fu_767_p1() {
    partial_products_0_7_fu_767_p1 = esl_zext<896,112>(grp_fu_727_p2.read());
}

void bc_mult_448::thread_partial_products_0_8_fu_771_p3() {
    partial_products_0_8_fu_771_p3 = esl_concat<112,56>(grp_fu_732_p2.read(), ap_const_lv56_0);
}

void bc_mult_448::thread_partial_products_0_9_fu_783_p3() {
    partial_products_0_9_fu_783_p3 = esl_concat<112,112>(grp_fu_737_p2.read(), ap_const_lv112_0);
}

void bc_mult_448::thread_tmp_1_fu_710_p9() {
    tmp_1_fu_710_p9 = i7_0_reg_396.read().range(3-1, 0);
}

void bc_mult_448::thread_trunc_ln215_fu_706_p1() {
    trunc_ln215_fu_706_p1 = i7_0_reg_396.read().range(3-1, 0);
}

void bc_mult_448::thread_trunc_ln44_fu_1379_p1() {
    trunc_ln44_fu_1379_p1 = i8_0_reg_503.read().range(3-1, 0);
}

void bc_mult_448::thread_zext_ln1503_1_fu_791_p1() {
    zext_ln1503_1_fu_791_p1 = esl_zext<896,224>(partial_products_0_9_fu_783_p3.read());
}

void bc_mult_448::thread_zext_ln1503_2_fu_803_p1() {
    zext_ln1503_2_fu_803_p1 = esl_zext<896,280>(partial_products_0_10_fu_795_p3.read());
}

void bc_mult_448::thread_zext_ln1503_3_fu_815_p1() {
    zext_ln1503_3_fu_815_p1 = esl_zext<896,336>(partial_products_0_11_fu_807_p3.read());
}

void bc_mult_448::thread_zext_ln1503_4_fu_827_p1() {
    zext_ln1503_4_fu_827_p1 = esl_zext<896,392>(partial_products_0_12_fu_819_p3.read());
}

void bc_mult_448::thread_zext_ln1503_5_fu_839_p1() {
    zext_ln1503_5_fu_839_p1 = esl_zext<896,448>(partial_products_0_13_fu_831_p3.read());
}

void bc_mult_448::thread_zext_ln1503_6_fu_851_p1() {
    zext_ln1503_6_fu_851_p1 = esl_zext<896,504>(partial_products_0_14_fu_843_p3.read());
}

void bc_mult_448::thread_zext_ln1503_fu_779_p1() {
    zext_ln1503_fu_779_p1 = esl_zext<896,168>(partial_products_0_8_fu_771_p3.read());
}

void bc_mult_448::thread_zext_ln215_1_fu_724_p1() {
    zext_ln215_1_fu_724_p1 = esl_zext<112,56>(tmp_1_reg_2168.read());
}

void bc_mult_448::thread_zext_ln215_2_fu_666_p1() {
    zext_ln215_2_fu_666_p1 = esl_zext<112,56>(ai_1_V_fu_522_p4.read());
}

void bc_mult_448::thread_zext_ln215_3_fu_670_p1() {
    zext_ln215_3_fu_670_p1 = esl_zext<112,56>(ai_2_V_fu_542_p4.read());
}

void bc_mult_448::thread_zext_ln215_4_fu_674_p1() {
    zext_ln215_4_fu_674_p1 = esl_zext<112,56>(ai_3_V_fu_562_p4.read());
}

void bc_mult_448::thread_zext_ln215_5_fu_678_p1() {
    zext_ln215_5_fu_678_p1 = esl_zext<112,56>(ai_4_V_fu_582_p4.read());
}

void bc_mult_448::thread_zext_ln215_6_fu_682_p1() {
    zext_ln215_6_fu_682_p1 = esl_zext<112,56>(ai_5_V_fu_602_p4.read());
}

void bc_mult_448::thread_zext_ln215_7_fu_686_p1() {
    zext_ln215_7_fu_686_p1 = esl_zext<112,56>(ai_6_V_fu_622_p4.read());
}

void bc_mult_448::thread_zext_ln215_8_fu_690_p1() {
    zext_ln215_8_fu_690_p1 = esl_zext<112,56>(ai_7_V_fu_642_p4.read());
}

void bc_mult_448::thread_zext_ln215_fu_662_p1() {
    zext_ln215_fu_662_p1 = esl_zext<112,56>(ai_0_V_fu_514_p1.read());
}

void bc_mult_448::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln28_fu_694_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln28_fu_694_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_1175_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXX";
            break;
    }
}

}

